spring:
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/images/**
#          filters:
#            - StripPrefix=1